name: Auto-Increment Version

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  call-reusable-workflow:
    uses: projectalita/actions/.github/workflows/versioneer.yml@main
    with:
      metadata_file: "metadata.json"
      version_key: ".version"
